// ./client/src/components/Footer.jsx
import React from "react";
import { Link } from "react-router-dom";

import './Footer.css';

export default function Navbar({ currentUser, onLogout }) {
    return (
        <footer className="footer-menu">
            <p>©ArchitectureShazam</p>
            <p>Disclaimer: All images and models generated utilise AI in the pipeline and are generated by AI.</p>
        </footer>
    );
}
